FROM ubuntu:24.04

# fix for ubuntu stupidly creating a default user
RUN touch /var/mail/ubuntu && chown ubuntu /var/mail/ubuntu && userdel -r ubuntu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y
RUN apt install -y apt-utils libssl-dev
RUN apt install -y build-essential cmake gdb valgrind
RUN apt install -y cppcheck python3-pip
RUN apt install -y wget vim
RUN apt install -y git clang clang-tidy clang-format

# Install Eigen
WORKDIR /install
RUN wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
RUN tar -xzf eigen-3.4.0.tar.gz
WORKDIR /install/eigen-3.4.0
RUN cmake -B build -S . -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DEIGEN_BUILD_BTL=OFF
WORKDIR /install/eigen-3.4.0/build
RUN make && make install

# Install Google Test
WORKDIR /install
RUN wget https://github.com/google/googletest/archive/refs/tags/v1.13.0.tar.gz
RUN tar -xzf v1.13.0.tar.gz
WORKDIR /install/googletest-1.13.0
RUN cmake -B build -S .
WORKDIR /install/googletest-1.13.0/build
RUN make && make install

# Install OpenCV
WORKDIR /install
RUN git clone https://github.com/opencv/opencv.git --depth 1 --branch 4.5.4
WORKDIR /install/opencv
RUN cmake -B build -S . \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr/local \
	-DOPENCV_GENERATE_PKGCONFIG=ON \
	-DBUILD_EXAMPLES=OFF \
	-DWITH_QT=OFF \
	-DBUILD_TESTS=OFF \
	-DBUILD_PERF_TESTS=OFF \
	-DBUILD_opencv_python2=OFF \
	-DBUILD_opencv_java=OFF \
	-DBUILD_opencv_apps=OFF
RUN cd build && make && make install
RUN lfconfig

WORKDIR /
RUN rm -rf install

# Install gcovr
RUN pip install gcovr

# Check running architecture
RUN dpkg --print-architecture
