FROM ubuntu:24.04

# fix for ubuntu stupidly creating a default user
RUN touch /var/mail/ubuntu && chown ubuntu /var/mail/ubuntu && userdel -r ubuntu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y
RUN apt install -y apt-utils
RUN apt install -y build-essential cmake gdb
RUN apt install -y valgrind
RUN apt install -y git wget vim
RUN apt install -y clang-tidy clang-format

WORKDIR /build
RUN wget https://github.com/oclint/oclint/releases/download/v24.11/oclint-24.11-llvm-16.0.4-x86_64-linux-ubuntu-24.04.tar.gz
RUN tar -xvf oclint-*.tar.gz
RUN mv oclint-*/ /opt/oclint
RUN rm oclint-*.tar.gz
ENV PATH="/opt/oclint/bin:${PATH}"

# Check running architecture
RUN dpkg --print-architecture
