FROM ghcr.io/jeffbrn/docker_env/dev_cpp_x86:1.0

ARG USERNAME
ARG ARG_UID
ARG ARG_GID

# Add host user to the container so that file permissions are correct
RUN groupadd -o --gid $ARG_GID $USERNAME \
    && useradd -l -s /bin/bash --uid $ARG_UID --gid $ARG_GID -m $USERNAME \
    && mkdir -p /etc/sudoers.d \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME
