services:
    cpp-dev-env:
        user: ${USER}
        container_name: cpp-user-dev
        image: cpp-user-dev_img
        build:
            context: .
            dockerfile: Dockerfile_user
            args:
                USERNAME: ${USER}
                ARG_UID: ${USER_UID}
                ARG_GID: ${USER_GID}
        network_mode: "host"
        volumes:
            - ..:/workspace
            - ${HOME}/.ssh:/home/${USER}/.ssh:ro
            - ${HOME}/.gitconfig:/home/${USER}/.gitconfig:ro
        command: tail -f /dev/null
